/* ══════════════════════════════════════════════════════════════
   Elsevier roundtable word cloud — app.js

   Needs: d3 v7 + d3-cloud 1.2.7 (CDN, see index.html)
          data/presets.js      generated by build-dataset.py
          data/manual-terms.js hand-edited — add your own terms there

   Colour carries meaning here rather than decoration:
     orange  the theme raised most often
     ink     raised more than once
     grey    raised once
     blue    added by hand, so not from the survey

   Two views of the same terms: 'phrases' and 'words'.
══════════════════════════════════════════════════════════════ */

'use strict';

/* One set of term colours per theme, plus the plate behind them.
   Keep these in step with --hi / --mid / --lo / --added in styles.css,
   which colour the legend swatches beside the cloud.

   PALETTE.light is also what a PNG export uses whatever the screen is
   set to, so an exported cloud always drops onto a white slide. */
const PALETTE = {
  light: { hi: '#FF551D', mid: '#1E1E1E', lo: '#7A736B', added: '#2354FF', paper: '#FFFFFF' },
  dark:  { hi: '#FF7043', mid: '#F2EFE9', lo: '#8E877D', added: '#7FA3FF', paper: '#171614' },
};

const THEME_KEY = 'roundtable.theme.v1';

const CLOUD_FONT   = "'IBM Plex Sans Condensed', 'IBM Plex Sans', Arial, sans-serif";
const CLOUD_WEIGHT = 600;

/* Type sizes for the cloud, quoted at a 900px-wide plate and scaled down
   proportionally on narrower ones. Without this, a phone keeps the desktop
   sizes and d3-cloud quietly drops every term that will not fit. */
const REF_WIDTH  = 900;
const REF_HEIGHT = 414;   // 900 x 0.46, the plate's resting aspect
const MIN_FONT   = 24;
const MAX_FONT   = 104;

/* Full screen the plate is roughly twice the reference width, and type
   quoted for 900px looks lost on it. The cap is what keeps the in-page
   plate at its designed sizes while letting the full-screen one scale
   up: without it, the whole page would grow with the window. */
const MAX_UPSCALE = 2.05;

function fontRange(width, height, cap) {
  // Both axes matter: a wide, shallow plate runs out of height first.
  const k = Math.min(cap, width / REF_WIDTH, height / REF_HEIGHT);
  return {
    min: Math.max(11, Math.round(MIN_FONT * k)),
    max: Math.max(30, Math.round(MAX_FONT * k)),
  };
}

const STORAGE_KEY = 'roundtable.addedTerms.v1';
const CUSTOM = '__custom__';

const DEFAULT_STOPWORDS = [
  'a','about','above','after','again','against','all','am','an','and',
  'any','are','as','at','be','because','been','before','being','below',
  'between','both','but','by','can','cannot','could','did','do','does',
  'doing','down','during','each','few','for','from','further','get','got',
  'had','has','have','having','he','her','here','hers','herself','him',
  'himself','his','how','i','if','in','into','is','it','its','itself',
  'me','more','most','my','myself','no','nor','not','of','off','on',
  'once','only','or','other','ought','our','ours','ourselves','out',
  'over','own','same','she','should','so','some','such','than','that',
  'the','their','theirs','them','themselves','then','there','these',
  'they','this','those','through','to','too','under','until','up','us',
  'very','was','we','were','what','when','where','which','while','who',
  'whom','why','will','with','would','you','your','yours','yourself',
  'yourselves',
];

/* ══ DOM ═══════════════════════════════════════════════════════ */
const $ = (id) => document.getElementById(id);

const plate       = $('plate');
const plateEmpty  = $('plate-empty');
const cloud       = $('cloud');
const capSource   = $('cap-source');
const legendAdded = $('legend-added');
const savePngBtn  = $('save-png');
const fitNote     = $('fit-note');
const themeToggle = $('theme-toggle');
const fsBtn       = $('plate-fs');

const switchOpts  = Array.from(document.querySelectorAll('.switch-opt'));

const drawer      = $('drawer');
const scrim       = $('scrim');
const drawerOpen  = $('drawer-open');
const drawerClose = $('drawer-close');

const presetSel   = $('preset');
const presetHint  = $('preset-hint');
const textInput   = $('text-input');
const dropzone    = $('dropzone');
const fileInput   = $('file-input');
const fileName    = $('file-name');
const stopwords   = $('stopwords');
const stopReset   = $('stopwords-reset');
const generateBtn = $('generate');
const generateLbl = $('generate-label');
const spin        = $('spin');
const startOver   = $('start-over');
const problem     = $('problem');

const addOpen  = $('add-open');
const addPanel = $('add-panel');
const addInput = $('add-input');
const addApply = $('add-apply');
const addCopy  = $('add-copy');
const addReset = $('add-reset');
const addNote  = $('add-note');

/* ══ STATE ═════════════════════════════════════════════════════ */
let layout   = null;
let viewMode = 'phrases';
let presetId = null;

const PRESETS = Array.isArray(window.WORDCLOUD_PRESETS) ? window.WORDCLOUD_PRESETS : [];

const activePreset = () => PRESETS.find(p => p.id === presetId) || null;

/* ══════════════════════════════════════════════════════════════
   THEME
   The inline script in index.html has already put data-theme on
   <html> before first paint, so all this does is read it, flip it,
   and recolour the cloud that is already drawn — no relayout, which
   is what keeps the switch instant.
══════════════════════════════════════════════════════════════ */

const theme = () => document.documentElement.getAttribute('data-theme') === 'dark' ? 'dark' : 'light';

const termColors = () => PALETTE[theme()];

function paintThemeToggle() {
  const dark = theme() === 'dark';
  themeToggle.setAttribute('aria-pressed', String(dark));
  // The button offers the other theme, so its label names that one.
  themeToggle.setAttribute('aria-label', dark ? 'Switch to light mode' : 'Switch to dark mode');
  themeToggle.title = dark ? 'Light mode' : 'Dark mode';
}

/** Recolours the drawn SVG in place. Each term carries data-tone, so the
    new colour is a lookup rather than a recomputation from the values. */
function recolorCloud() {
  const svg = cloud.querySelector('svg');
  if (!svg) return;
  const c = termColors();
  const bg = svg.querySelector('.cloud-bg');
  if (bg) bg.setAttribute('fill', c.paper);
  for (const t of svg.querySelectorAll('text')) {
    t.setAttribute('fill', c[t.dataset.tone] || c.mid);
  }
}

function setTheme(next, { remember = true } = {}) {
  document.documentElement.setAttribute('data-theme', next === 'dark' ? 'dark' : 'light');
  if (remember) {
    try { localStorage.setItem(THEME_KEY, next); } catch { /* private mode */ }
  }
  paintThemeToggle();
  recolorCloud();
}

/* ══════════════════════════════════════════════════════════════
   TERMS ADDED BY HAND
   Two sources, merged: data/manual-terms.js (committed, everyone
   sees it) and localStorage (this browser only, added on the page).
══════════════════════════════════════════════════════════════ */

/** "Term | 3" -> {text:'Term', value:3}. "# note" and blanks are skipped. */
function parseTerms(text) {
  if (!text) return [];
  return text.split('\n')
    .map(l => l.trim())
    .filter(l => l && !l.startsWith('#'))
    .map(l => {
      const [label, weight] = l.split('|');
      const t = label.trim();
      return t ? { text: t, value: Math.max(1, Math.round(Number(weight)) || 1) } : null;
    })
    .filter(Boolean);
}

function readStored() {
  try { return localStorage.getItem(STORAGE_KEY) || ''; } catch { return ''; }
}

function writeStored(text) {
  try {
    if (text.trim()) localStorage.setItem(STORAGE_KEY, text);
    else localStorage.removeItem(STORAGE_KEY);
    return true;
  } catch { return false; }
}

function addedTerms() {
  return mergeTerms(
    parseTerms(window.WORDCLOUD_MANUAL_TERMS || ''),
    parseTerms(readStored())
  );
}

/** Highest weight wins for duplicates. */
function mergeTerms(base, extra) {
  const seen = new Map();
  for (const t of [...base, ...extra]) {
    const key = t.text.toLowerCase();
    const hit = seen.get(key);
    if (hit) {
      hit.value = Math.max(hit.value, t.value);
      hit.added = hit.added && t.added;
    } else {
      seen.set(key, { ...t });
    }
  }
  return Array.from(seen.values());
}

/* ══ TEXT PROCESSING ═══════════════════════════════════════════ */

function stopSet() {
  return new Set(stopwords.value.split(',').map(w => w.trim().toLowerCase()).filter(Boolean));
}

/** Single-words view: word frequency across the corpus. */
function countWords(text) {
  const stops = stopSet();
  const freq = {};
  for (const t of text.toLowerCase().replace(/[^a-z\s]/g, ' ').split(/\s+/)) {
    if (t.length > 1 && !stops.has(t)) freq[t] = (freq[t] || 0) + 1;
  }
  return Object.entries(freq)
    .map(([text, value]) => ({ text, value }))
    .sort((a, b) => b.value - a.value);
}

/** Phrases view for free text: people separate terms with , ; . / or newlines. */
function countPhrases(text) {
  const seen = new Map();
  for (const part of text.split(/[,;.\n\/]+/)) {
    const phrase = part.trim().replace(/\s+/g, ' ').replace(/^[?!\s]+|[?!\s]+$/g, '');
    if (phrase.length < 2) continue;
    const key = phrase.toLowerCase();
    const hit = seen.get(key);
    if (hit) hit.value += 1;
    else seen.set(key, { text: phrase, value: 1 });
  }
  return Array.from(seen.values()).sort((a, b) => b.value - a.value);
}

/** Builds the term list for the current source and view. */
function buildTerms() {
  const preset = activePreset();
  const added  = addedTerms().map(t => ({ ...t, added: true }));

  if (viewMode !== 'words') {
    const base = preset
      ? preset.phrases.map(p => ({ ...p, added: false }))
      : countPhrases(textInput.value.trim()).map(p => ({ ...p, added: false }));
    return mergeTerms(base, added).sort((a, b) => b.value - a.value);
  }

  // Single words: fold the added terms into the corpus, repeated by weight,
  // so their size reflects the weight that was asked for.
  const corpus = preset ? preset.sourceText : textInput.value.trim();
  const addedCorpus = added.map(t => Array(t.value).fill(t.text).join(' ')).join(' ');

  // A word counts as added only if it appears nowhere in the survey corpus.
  const corpusWords = new Set(countWords(corpus).map(w => w.text));
  return countWords(`${corpus} ${addedCorpus}`)
    .map(w => ({ ...w, added: !corpusWords.has(w.text) }));
}

/* ══ RENDER ════════════════════════════════════════════════════ */

function sizeScale(terms, range) {
  if (!terms.length) return () => range.min;
  const hi = terms[0].value;
  const lo = terms[terms.length - 1].value;
  if (hi === lo) return () => Math.round((range.min + range.max) / 2);
  return v => Math.round(range.min + ((v - lo) / (hi - lo)) * (range.max - range.min));
}

/**
 * A long phrase at full size can be wider than the plate, and d3-cloud
 * silently drops whatever it cannot place. Cap each term to what fits so
 * no term goes missing.
 */
function fitWidth(size, text, width, floor) {
  const RATIO = 0.5; // condensed semibold, measured
  return Math.max(floor, Math.min(size, Math.floor((width * 0.94) / (RATIO * Math.max(text.length, 1)))));
}

/**
 * Which band a term falls in — 'hi', 'mid', 'lo' or 'added'. The band is
 * what gets stored on the element; the hex is looked up from the band, so
 * switching theme or exporting a PNG only changes the lookup table.
 */
function termTone(term, hi, lo) {
  if (term.added) return 'added';
  if (hi === lo) return 'mid';
  if (term.value === hi) return 'hi';
  return term.value > lo ? 'mid' : 'lo';
}

function render(terms) {
  if (layout) { layout.stop(); layout = null; }

  /* In the page the plate's height is derived from its width, which keeps
     the figure a fixed aspect however the window is sized. Full screen it
     is the screen, so the real measured height is used and the cloud fills
     the display edge to edge. */
  const full   = isFullscreen();
  const width  = plate.clientWidth || 1100;
  const height = full
    ? (plate.clientHeight || Math.max(Math.round(width * 0.46), 320))
    : Math.max(Math.round(width * 0.46), 320);
  const range  = fontRange(width, height, full ? MAX_UPSCALE : 1);
  const scale  = sizeScale(terms, range);
  const hi = terms[0].value;
  const lo = terms[terms.length - 1].value;

  const floor = Math.min(range.min, 13);

  const buildWords = (shrink) => terms.map(t => ({
    text:  t.text,
    value: t.value,
    added: !!t.added,
    size:  Math.max(floor, Math.round(fitWidth(scale(t.value), t.text, width, floor) * shrink)),
    tone:  termTone(t, hi, lo),
  }));

  /* d3-cloud drops any term it cannot place, and whether a term fits depends
     on how the ones before it happened to pack. Rather than tune the size
     constants until it works for this one dataset, shrink and try again until
     everything lands — which keeps working as terms are added. */
  const MIN_SHRINK = 0.5;
  let words = [];

  function attempt(shrink) {
    if (layout) { layout.stop(); layout = null; }
    words = buildWords(shrink);

    layout = d3.layout.cloud()
      .size([width, height])
      .words(words)
      .padding(7)
      .rotate(0)
      .font(CLOUD_FONT)
      .fontWeight(CLOUD_WEIGHT)
      .fontSize(d => d.size)
      .spiral('archimedean')
      .on('end', placed => {
        if (placed.length < words.length && shrink > MIN_SHRINK) {
          attempt(shrink * 0.9);
          return;
        }
        draw(placed);
      })
      .start();
  }

  attempt(1);

  function draw(placed) {
    cloud.innerHTML = '';
    const c = termColors();

    const svg = d3.select(cloud).append('svg')
      .attr('xmlns', 'http://www.w3.org/2000/svg')
      .attr('viewBox', `0 0 ${width} ${height}`)
      .attr('width', width)
      .attr('height', height);

    svg.append('rect')
      .attr('class', 'cloud-bg')
      .attr('width', width).attr('height', height)
      .attr('fill', c.paper);

    svg.append('g')
        .attr('class', 'cloud-stage')
        .attr('transform', `translate(${width / 2},${height / 2})`)
      .selectAll('text')
      .data(placed)
      .enter()
      .append('text')
        .attr('text-anchor', 'middle')
        .attr('font-family', CLOUD_FONT)
        .attr('font-weight', CLOUD_WEIGHT)
        .attr('font-size', d => `${d.size}px`)
        .attr('fill', d => c[d.tone] || c.mid)
        .attr('data-tone', d => d.tone)
        /* Resting position and size, kept so the PNG export can put every
           term back where it belongs. */
        .attr('data-bx', d => d.x)
        .attr('data-by', d => d.y)
        .attr('data-bs', d => d.size)
        .attr('transform', d => `translate(${d.x},${d.y})`)
        .text(d => d.text)
      .append('title')
        .text(d => d.added
          ? `${d.text} — added by hand`
          : `${d.text} — raised ${d.value} time${d.value !== 1 ? 's' : ''}`);

    cloud.style.display = 'block';
    plateEmpty.style.display = 'none';
    savePngBtn.disabled = false;

    // The notice belongs next to the cloud, not in the drawer — the drawer is
    // shut by the time anyone reads this.
    const missed = words.length - placed.length;
    if (missed > 0) {
      const names = words.filter(w => !placed.includes(w)).map(w => w.text).join(', ');
      say(fitNote, `${missed} term${missed !== 1 ? 's did' : ' did'} not fit: ${names}. Widen the window, or shorten the longest of them.`, 'warn');
    } else {
      hide(fitNote);
    }
  }
}

/** Recomputes and redraws from current state. */
function refresh({ announce = false } = {}) {
  const terms = buildTerms();

  if (!terms.length) {
    cloud.innerHTML = '';
    cloud.style.display = 'none';
    plateEmpty.style.display = 'block';
    savePngBtn.disabled = true;
    hide(fitNote);
    if (announce) {
      say(problem, viewMode === 'phrases'
        ? 'There is nothing to draw yet. Paste some text, drop in a file, or add a term by hand.'
        : 'Every word was filtered out. Remove some entries from "Words to ignore", or add more text.', 'bad');
    }
    updateCaption();
    return;
  }

  hide(problem);
  render(terms);
  updateCaption();
}

/* ══════════════════════════════════════════════════════════════
   FULL SCREEN

   One click puts the cloud on the whole screen with nothing else on it:
   the top bar, the caption and the buttons under the plate are all
   outside the element that goes full screen, so they simply are not
   there. The Fullscreen API is prefixed on older WebKit, hence the
   small shims.

   The cloud is laid out again rather than scaled up. Scaling a 1180px
   layout to 1920 would leave the same gaps and the same type
   relationships, just bigger and softer; re-running d3-cloud at the new
   size repacks the terms and re-quotes the type for the screen, which is
   the whole point of doing this on a projector.
══════════════════════════════════════════════════════════════ */

const fsElement = () =>
  document.fullscreenElement || document.webkitFullscreenElement || null;

const isFullscreen = () => fsElement() === plate;

function paintFsButton() {
  const on = isFullscreen();
  plate.classList.toggle('is-fs', on);
  fsBtn.setAttribute('aria-pressed', String(on));
  fsBtn.setAttribute('aria-label', on ? 'Leave full screen' : 'Show the cloud full screen');
  fsBtn.title = on ? 'Leave full screen (Esc)' : 'Full screen (F)';
}

function toggleFullscreen() {
  if (isFullscreen()) {
    const exit = document.exitFullscreen || document.webkitExitFullscreen;
    if (exit) exit.call(document);
    return;
  }

  const req = plate.requestFullscreen || plate.webkitRequestFullscreen;
  if (!req) {
    // Kiosk browsers and a few embeds refuse it. Say so rather than
    // leaving a button that does nothing when pressed.
    say(fitNote, 'This browser will not let the page go full screen. Use its own full-screen control instead — F11 on Windows.', 'warn');
    return;
  }

  // Firefox rejects rather than throws, so both paths need catching.
  try {
    const r = req.call(plate);
    if (r && typeof r.catch === 'function') r.catch(() => {});
  } catch { /* refused — paintFsButton never runs, so nothing to undo */ }
}

/* Entering and leaving both change the plate's size, so the cloud has to
   be laid out again either way. Deferred a frame because the browser
   reports the change before it has finished resizing the element, and
   reading clientWidth too early lays the cloud out for the old box. */
function onFullscreenChange() {
  paintFsButton();
  requestAnimationFrame(() => {
    requestAnimationFrame(() => {
      if (cloud.style.display !== 'none' && cloud.querySelector('svg')) refresh();
    });
  });
}

/* ══ CAPTION ═══════════════════════════════════════════════════ */

function updateCaption() {
  const preset = activePreset();
  const added  = addedTerms();

  legendAdded.hidden = added.length === 0;

  if (preset) {
    /* Named, not itemised. The room does not need the file name, the sheet
       and the extraction date under the figure; what it needs to know is
       that these are their own words, taken from the question they were
       asked. The full provenance stays in the repository README. */
    capSource.textContent = 'Source: Poll, "Keywords – what\'s on your mind?"';
  } else {
    const name = fileName.textContent.trim();
    capSource.textContent = name
      ? `Source: the file "${name}", read in this browser and not uploaded anywhere.`
      : 'Source: text typed or pasted into this page.';
  }
}

/* ══ SOURCE PICKER ═════════════════════════════════════════════ */

function initPresets() {
  presetSel.innerHTML = '';

  for (const p of PRESETS) {
    const o = document.createElement('option');
    o.value = p.id;
    o.textContent = p.label;
    presetSel.appendChild(o);
  }

  const custom = document.createElement('option');
  custom.value = CUSTOM;
  custom.textContent = 'My own text or file';
  presetSel.appendChild(custom);

  presetId = PRESETS.length ? PRESETS[0].id : null;
  presetSel.value = presetId || CUSTOM;
  updatePresetHint();
}

function updatePresetHint() {
  const p = activePreset();
  presetHint.textContent = p
    ? `${p.responseCount} answers, ${p.phrases.length} terms.`
    : 'Drawn from whatever you paste or upload below.';
}

function useCustom() {
  presetId = null;
  presetSel.value = CUSTOM;
  updatePresetHint();
}

/* ══ VIEW SWITCH ═══════════════════════════════════════════════ */

function paintSwitch() {
  for (const b of switchOpts) {
    const on = b.dataset.view === viewMode;
    b.classList.toggle('is-on', on);
    b.setAttribute('aria-selected', String(on));
  }
}

const VIEWS = ['phrases', 'words'];

function setView(mode, { redraw = true } = {}) {
  if (!VIEWS.includes(mode)) return;
  if (mode === viewMode && redraw) return;
  viewMode = mode;
  paintSwitch();

  // Keep the view in the URL so a link can point straight at either one.
  try {
    const url = new URL(location.href);
    url.searchParams.set('view', mode);
    history.replaceState(null, '', url);
  } catch { /* not worth failing the render over */ }

  if (redraw) refresh();
}

/* ══ DRAWER ════════════════════════════════════════════════════ */

let lastFocus = null;

function openDrawer() {
  lastFocus = document.activeElement;
  drawer.hidden = false;
  scrim.hidden = false;
  drawerOpen.setAttribute('aria-expanded', 'true');
  document.body.style.overflow = 'hidden';
  presetSel.focus();
}

function closeDrawer() {
  drawer.hidden = true;
  scrim.hidden = true;
  drawerOpen.setAttribute('aria-expanded', 'false');
  document.body.style.overflow = '';
  if (lastFocus) lastFocus.focus();
}

/* ══ ACTIONS ═══════════════════════════════════════════════════ */

function handleGenerate() {
  const raw = textInput.value.trim();
  if (raw && presetId) useCustom();

  if (!raw && !presetId && !addedTerms().length) {
    say(problem, 'Paste some text, choose a file, or pick a source above first.', 'bad');
    return;
  }

  busy(true);
  // Lets the spinner paint before the synchronous layout run.
  setTimeout(() => {
    refresh({ announce: true });
    busy(false);
    if (problem.hidden) closeDrawer(); // nothing went wrong, so get out of the way
  }, 30);
}

function handleStartOver() {
  textInput.value = '';
  fileName.textContent = '';
  fileInput.value = '';
  hide(problem);
  presetId = PRESETS.length ? PRESETS[0].id : null;
  presetSel.value = presetId || CUSTOM;
  updatePresetHint();
  refresh();
}

/**
 * The export copy: light palette, white plate, every term back at its
 * resting position at full opacity. So a PNG is the same picture whether
 * it was taken in dark mode or light, and it drops straight onto a white
 * Elsevier slide.
 */
function exportSvg(svg) {
  const copy = svg.cloneNode(true);
  const c = PALETTE.light;

  const bg = copy.querySelector('.cloud-bg');
  if (bg) bg.setAttribute('fill', c.paper);

  const stage = copy.querySelector('.cloud-stage');
  if (stage) {
    const w = parseInt(copy.getAttribute('width'), 10) || 1100;
    const h = parseInt(copy.getAttribute('height'), 10) || 560;
    stage.setAttribute('transform', `translate(${w / 2},${h / 2})`);
  }

  for (const t of copy.querySelectorAll('text')) {
    t.setAttribute('fill', c[t.dataset.tone] || c.mid);
    t.setAttribute('opacity', '1');
    t.setAttribute('transform', `translate(${t.dataset.bx || 0},${t.dataset.by || 0})`);
  }

  return copy;
}

function handleSavePng() {
  const svg = cloud.querySelector('svg');
  if (!svg) return;

  const w = parseInt(svg.getAttribute('width'), 10) || 1100;
  const h = parseInt(svg.getAttribute('height'), 10) || 560;
  const k = 2; // 2x, so it holds up in a deck or in print

  const canvas = document.createElement('canvas');
  canvas.width = w * k;
  canvas.height = h * k;

  const ctx = canvas.getContext('2d');
  ctx.scale(k, k);
  ctx.fillStyle = '#FFFFFF';
  ctx.fillRect(0, 0, w, h);

  const blob = new Blob([new XMLSerializer().serializeToString(exportSvg(svg))], { type: 'image/svg+xml;charset=utf-8' });
  const url  = URL.createObjectURL(blob);
  const img  = new Image();
  const name = `${presetId || 'wordcloud'}-${viewMode}`;

  img.onload = () => {
    ctx.drawImage(img, 0, 0, w, h);
    URL.revokeObjectURL(url);
    const a = document.createElement('a');
    a.download = `${name}.png`;
    a.href = canvas.toDataURL('image/png');
    a.click();
  };

  img.onerror = () => {
    URL.revokeObjectURL(url);
    const a = document.createElement('a');
    a.download = `${name}.svg`;
    a.href = URL.createObjectURL(blob);
    a.click();
  };

  img.src = url;
}

function handleFile(file) {
  if (!file) return;

  const ext = file.name.slice(file.name.lastIndexOf('.')).toLowerCase();
  if (!['.txt', '.csv'].includes(ext)) {
    say(problem, `"${file.name}" is not a .txt or .csv file. Save it as one of those and try again.`, 'bad');
    return;
  }

  const reader = new FileReader();
  reader.onload = e => {
    textInput.value = e.target.result;
    fileName.textContent = file.name;
    useCustom();
    hide(problem);
    refresh();
  };
  reader.onerror = () => say(problem, `Could not read "${file.name}". Try choosing it again.`, 'bad');
  reader.readAsText(file);
}

/* ══ ADD A TERM ════════════════════════════════════════════════ */

function handleAddApply() {
  const text = addInput.value.trim();
  const parsed = parseTerms(text);

  if (!parsed.length) {
    say(addNote, 'Type at least one term, one per line.', 'warn');
    return;
  }

  const combined = [readStored().trim(), text].filter(Boolean).join('\n');
  const stored = writeStored(combined);

  addInput.value = '';
  refresh();

  const n = parsed.length;
  say(addNote,
    stored
      ? `Added ${n} term${n !== 1 ? 's' : ''}. They are saved in this browser.`
      : `Added ${n} term${n !== 1 ? 's' : ''}, but this browser will not let the page save them, so they go when you reload.`,
    stored ? 'ok' : 'warn');
}

function handleAddCopy() {
  const all = [readStored().trim(), addInput.value.trim()].filter(Boolean).join('\n');

  if (!all) {
    say(addNote, 'There are no added terms to copy yet.', 'warn');
    return;
  }

  const snippet = 'window.WORDCLOUD_MANUAL_TERMS = `\n'
    + all.split('\n').map(l => `  ${l.trim()}`).join('\n')
    + '\n`;';

  navigator.clipboard.writeText(snippet).then(
    () => say(addNote, 'Copied. Paste it over the block in data/manual-terms.js, then commit and push.', 'ok'),
    () => say(addNote, 'This browser blocked the clipboard. Select the terms above and copy them yourself.', 'warn')
  );
}

function handleAddReset() {
  writeStored('');
  addInput.value = '';
  refresh();
  say(addNote, 'Removed the terms you added here. Terms in data/manual-terms.js stay.', 'ok');
}

/* ══ SMALL HELPERS ═════════════════════════════════════════════ */

/* kind: 'bad' | 'warn' | 'info' | anything else for the ok tone.
   Note that this rewrites the class list, so per-element styling in
   styles.css has to be hung off the id. */
function say(el, msg, kind) {
  el.textContent = msg;
  el.className = 'note' + (kind === 'bad' ? ' note-bad' : kind === 'warn' ? ' note-warn' : '');
  el.hidden = false;
}

function hide(el) { el.textContent = ''; el.hidden = true; }

function busy(state) {
  generateBtn.disabled = state;
  generateLbl.textContent = state ? 'Drawing' : 'Draw the cloud';
  spin.hidden = !state;
}

/* ══ WIRING ════════════════════════════════════════════════════ */

for (const b of switchOpts) b.addEventListener('click', () => setView(b.dataset.view));

themeToggle.addEventListener('click', () => setTheme(theme() === 'dark' ? 'light' : 'dark'));

fsBtn.addEventListener('click', toggleFullscreen);
document.addEventListener('fullscreenchange', onFullscreenChange);
document.addEventListener('webkitfullscreenchange', onFullscreenChange);

drawerOpen.addEventListener('click', openDrawer);
drawerClose.addEventListener('click', closeDrawer);
scrim.addEventListener('click', closeDrawer);

document.addEventListener('keydown', e => {
  if (e.key === 'Escape' && !drawer.hidden) closeDrawer();

  /* F for full screen — but not while someone is typing into the drawer
     or the add-a-term box, and not on top of a modifier chord. */
  if ((e.key === 'f' || e.key === 'F') && !e.ctrlKey && !e.metaKey && !e.altKey) {
    const el = document.activeElement;
    const typing = el && (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA' ||
                          el.tagName === 'SELECT' || el.isContentEditable);
    if (!typing) { e.preventDefault(); toggleFullscreen(); }
  }
});

presetSel.addEventListener('change', () => {
  presetId = presetSel.value === CUSTOM ? null : presetSel.value;
  updatePresetHint();
  refresh();
});

generateBtn.addEventListener('click', handleGenerate);
startOver.addEventListener('click', handleStartOver);
savePngBtn.addEventListener('click', handleSavePng);

stopReset.addEventListener('click', () => {
  stopwords.value = DEFAULT_STOPWORDS.join(', ');
  if (viewMode === 'words') refresh();
});

textInput.addEventListener('keydown', e => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') handleGenerate();
});

dropzone.addEventListener('click', () => fileInput.click());
dropzone.addEventListener('keydown', e => {
  if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); fileInput.click(); }
});
dropzone.addEventListener('dragover', e => { e.preventDefault(); dropzone.classList.add('is-over'); });
dropzone.addEventListener('dragleave', e => {
  if (!dropzone.contains(e.relatedTarget)) dropzone.classList.remove('is-over');
});
dropzone.addEventListener('drop', e => {
  e.preventDefault();
  dropzone.classList.remove('is-over');
  handleFile(e.dataTransfer.files[0]);
});
fileInput.addEventListener('change', () => handleFile(fileInput.files[0]));

addOpen.addEventListener('click', () => {
  const open = addPanel.hidden;
  addPanel.hidden = !open;
  addOpen.setAttribute('aria-expanded', String(open));
  addOpen.textContent = open ? 'Hide' : 'Add a term';
  if (open) addInput.focus();
});

addApply.addEventListener('click', handleAddApply);
addCopy.addEventListener('click', handleAddCopy);
addReset.addEventListener('click', handleAddReset);
addInput.addEventListener('keydown', e => {
  if ((e.ctrlKey || e.metaKey) && e.key === 'Enter') handleAddApply();
});

let resizeTimer;
window.addEventListener('resize', () => {
  clearTimeout(resizeTimer);
  resizeTimer = setTimeout(() => {
    if (cloud.style.display !== 'none' && cloud.querySelector('svg')) refresh();
  }, 250);
});

/* ══ START ═════════════════════════════════════════════════════ */

stopwords.value = DEFAULT_STOPWORDS.join(', ');
paintThemeToggle();
paintFsButton();
initPresets();

// ?view=words opens straight on that cut.
const wanted = new URLSearchParams(location.search).get('view');
if (VIEWS.includes(wanted)) {
  viewMode = wanted;
  paintSwitch();
}

// d3-cloud measures text on a canvas, so the webfont has to be loaded
// before the layout runs or every term is measured at the fallback width.
if (document.fonts && document.fonts.ready) {
  document.fonts.ready.then(() => refresh());
} else {
  refresh();
}
